name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Release binary
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            artifact_name: hibou
            asset_name: hibou-x86_64-unknown-linux-gnu
          - target: x86_64-unknown-linux-musl
            artifact_name: hibou
            asset_name: hibou-x86_64-unknown-linux-musl
          - target: x86_64-pc-windows-msvc
            artifact_name: hibou.exe
            asset_name: hibou-x86_64-pc-windows-msvc
          - target: x86_64-apple-darwin
            artifact_name: hibou
            asset_name: hibou-x86_64-apple-darwin

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - uses: Swatinem/rust-cache@v1

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }} --all-features --verbose

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@2.1.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true
