name: Release

on: push

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - uses: Swatinem/rust-cache@v1

      - name: Build
        run: cargo build --all --release

      - uses: actions/upload-artifact@v2
        with:
          name: hibou-x86_64-pc-windows
          path: target/release/hibou.exe

  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build static
        uses: stevenleadbeater/rust-musl-builder@master
        with:
          args: /bin/bash -c "cargo build --release --target=x86_64-unknown-linux-musl"

      - uses: actions/upload-artifact@v2
        with:
          name: hibou-x86_64-unknown-linux-musl
          path: target/x86_64-unknown-linux-musl/release/hibou
